# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b974627aa27a09308b1a2a9305784a4aa54716bf8ff486cad273d22f84ffe9842582d96078b681b181f61a7b2d9b82047cd8085c4c9d9412755acbf83032054d

test:
  secret_key_base: 49d0ec7dea815cbc9f8421d005fda6ab95c3bb0cee7d50e52bcf138f61cb6a6c34983f0ae23aada971cd9e3d0cd8bb1d983a1f29237e72dbade0aecf243769d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
